/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import AppPackage.AnimationClass;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author panay
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jControlPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jControlpanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFondo = new javax.swing.JPanel();
        jbtnCerrar = new javax.swing.JButton();
        jbtnMinimizar = new javax.swing.JButton();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jControlPanel.setPreferredSize(new java.awt.Dimension(190, 500));
        jControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/afiliacion.png"))); // NOI18N
        jControlPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mapa.png"))); // NOI18N
        jControlPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/factura.png"))); // NOI18N
        jControlPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tarjeta-de-socio-de-la-piscina.png"))); // NOI18N
        jControlPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/equipo.png"))); // NOI18N
        jControlPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(110, 15, 27));
        jLabel5.setText("Registrar visita");
        jControlPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 40));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(110, 15, 27));
        jLabel6.setText("Croquis");
        jControlPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 40));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(110, 15, 27));
        jLabel7.setText("Factura");
        jControlPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 40));

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 15, 27));
        jLabel3.setText("Membresia");
        jControlPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 30));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 15, 27));
        jLabel4.setText("Residente");
        jControlPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 160, 40));

        jControlpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu (1).png"))); // NOI18N
        jControlpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jControlpanelMouseClicked(evt);
            }
        });
        jControlPanel.add(jControlpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jControlPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 497));

        getContentPane().add(jControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-155, 0, 190, 497));

        jFondo.setPreferredSize(new java.awt.Dimension(1098, 538));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton-cerrar (1).png"))); // NOI18N
        jbtnCerrar.setBorderPainted(false);
        jbtnCerrar.setContentAreaFilled(false);
        jbtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCerrarMouseClicked(evt);
            }
        });
        jFondo.add(jbtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        jbtnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar (4).png"))); // NOI18N
        jbtnMinimizar.setBorderPainted(false);
        jbtnMinimizar.setContentAreaFilled(false);
        jbtnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnMinimizarMouseClicked(evt);
            }
        });
        jFondo.add(jbtnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 40, 40));

        jblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jblFondo.setMaximumSize(new java.awt.Dimension(1000, 497));
        jFondo.add(jblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCerrarMouseClicked
        // TODO add your handling code here:
        try{
          int dialogButton=JOptionPane.YES_NO_OPTION;
          int result= JOptionPane.showConfirmDialog(this, "Seguro que desea salir","EXIT",dialogButton);
          if(result==0){
              System.exit(0);
          }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jbtnCerrarMouseClicked

    private void jbtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMinimizarMouseClicked
        // TODO add your handling code here:
          this.setState(Formularios.Login.ICONIFIED);
    }//GEN-LAST:event_jbtnMinimizarMouseClicked

        public void jPanelXLeft(final int start, final int stop, final int delay, final int increment, final JPanel jPanel)
  {
    if (jPanel.getX() == start) {
      new Thread()
      {

        public void run()
        {
          while (jPanel.getX() > stop) {
            for (int i = start; i >= stop; i -= increment) {
              try
              {
                Thread.sleep(delay);
                jPanel.setLocation(i, jPanel.getY());
              }
              catch (InterruptedException e)
              {
                System.out.println("Error Thread Interrupted: " + e);
              }
            }
          }
          jPanel.setLocation(stop, jPanel.getY());
        }
      }.start();
    }
  }
  
    
    
    public void jPanelXRight(final int start, final int stop, final int delay, final int increment, final JPanel jPanel)
  {
    if (jPanel.getX() == start) {
      new Thread()
      {

        public void run()
        {
          while (jPanel.getX() > stop) {
            for (int i = start; i >= stop; i -= increment) {
              try
              {
                Thread.sleep(delay);
                jPanel.setLocation(i, jPanel.getY());
              }
              catch (InterruptedException e)
              {
                System.out.println("Error Thread Interrupted: " + e);
              }
            }
          }
          jPanel.setLocation(stop, jPanel.getY());
        }
      }.start();
    }
  }
  
    
    private void jControlpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jControlpanelMouseClicked
        // TODO add your handling code here:
        jPanelXRight(-155,0,10,5,jControlPanel);
        jPanelXLeft(0,-155,10,5,jControlPanel);
    }//GEN-LAST:event_jControlpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jControlPanel;
    private javax.swing.JLabel jControlpanel;
    private javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnMinimizar;
    // End of variables declaration//GEN-END:variables
}
